# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common_tensor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common_tensor.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13\x63ommon_tensor.proto\"9\n\x0c\x43ommonTensor\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05shape\x18\x02 \x03(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\x02\",\n\rCommonTensors\x12\x1b\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\r.CommonTensorb\x06proto3')
)




_COMMONTENSOR = _descriptor.Descriptor(
  name='CommonTensor',
  full_name='CommonTensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='CommonTensor.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shape', full_name='CommonTensor.shape', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='CommonTensor.data', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=80,
)


_COMMONTENSORS = _descriptor.Descriptor(
  name='CommonTensors',
  full_name='CommonTensors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='CommonTensors.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=126,
)

_COMMONTENSORS.fields_by_name['data'].message_type = _COMMONTENSOR
DESCRIPTOR.message_types_by_name['CommonTensor'] = _COMMONTENSOR
DESCRIPTOR.message_types_by_name['CommonTensors'] = _COMMONTENSORS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CommonTensor = _reflection.GeneratedProtocolMessageType('CommonTensor', (_message.Message,), dict(
  DESCRIPTOR = _COMMONTENSOR,
  __module__ = 'common_tensor_pb2'
  # @@protoc_insertion_point(class_scope:CommonTensor)
  ))
_sym_db.RegisterMessage(CommonTensor)

CommonTensors = _reflection.GeneratedProtocolMessageType('CommonTensors', (_message.Message,), dict(
  DESCRIPTOR = _COMMONTENSORS,
  __module__ = 'common_tensor_pb2'
  # @@protoc_insertion_point(class_scope:CommonTensors)
  ))
_sym_db.RegisterMessage(CommonTensors)


# @@protoc_insertion_point(module_scope)
